### ISSUE TITLE
Clicking on the forum categories lead to a 404.

### ISSUE THREAD

**Issue by TERIHAX** [davve77/BetterWRD#1]
![image](https://github.com/davve77/BetterWRD/assets/69073505/14652a3b-21fc-4345-a592-5856ee63c280)

clicking on the forum thread categories lead to a 404 page,

example. with BetterWRD, click on the marketplace forum category leads to: https://forum.wearedevs.net/forum/normalsellers
but without BetterWRD, it leads to (which is the one its supposed to go to) https://forum.wearedevs.net/c/9

**Comment by davve77** [comment]
this (as well as other) bugs will be fixed in the upcoming release, which i'd like to get out as soon as i can (just have to write a thread for it to announce it). in the meantime, i recommend that you disable "Old Forum Page layout" in betterwrd settings as a temporary workaround
